/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSentRouteImport } from './routes/_authenticated/sent'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedGiftIdRouteImport } from './routes/_authenticated/gift.$id'
import { Route as AuthenticatedFriendsFriendIdRouteImport } from './routes/_authenticated/friends_.$friendId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSentRoute = AuthenticatedSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGiftIdRoute = AuthenticatedGiftIdRouteImport.update({
  id: '/gift/$id',
  path: '/gift/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsFriendIdRoute =
  AuthenticatedFriendsFriendIdRouteImport.update({
    id: '/friends_/$friendId',
    path: '/friends/$friendId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/sent': typeof AuthenticatedSentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/friends/$friendId': typeof AuthenticatedFriendsFriendIdRoute
  '/gift/$id': typeof AuthenticatedGiftIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/sent': typeof AuthenticatedSentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/friends/$friendId': typeof AuthenticatedFriendsFriendIdRoute
  '/gift/$id': typeof AuthenticatedGiftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/sent': typeof AuthenticatedSentRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/friends_/$friendId': typeof AuthenticatedFriendsFriendIdRoute
  '/_authenticated/gift/$id': typeof AuthenticatedGiftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/friends'
    | '/sent'
    | '/settings'
    | '/friends/$friendId'
    | '/gift/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/friends'
    | '/sent'
    | '/settings'
    | '/'
    | '/friends/$friendId'
    | '/gift/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/friends'
    | '/_authenticated/sent'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/friends_/$friendId'
    | '/_authenticated/gift/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sent': {
      id: '/_authenticated/sent'
      path: '/sent'
      fullPath: '/sent'
      preLoaderRoute: typeof AuthenticatedSentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gift/$id': {
      id: '/_authenticated/gift/$id'
      path: '/gift/$id'
      fullPath: '/gift/$id'
      preLoaderRoute: typeof AuthenticatedGiftIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends_/$friendId': {
      id: '/_authenticated/friends_/$friendId'
      path: '/friends/$friendId'
      fullPath: '/friends/$friendId'
      preLoaderRoute: typeof AuthenticatedFriendsFriendIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedSentRoute: typeof AuthenticatedSentRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFriendsFriendIdRoute: typeof AuthenticatedFriendsFriendIdRoute
  AuthenticatedGiftIdRoute: typeof AuthenticatedGiftIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedSentRoute: AuthenticatedSentRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFriendsFriendIdRoute: AuthenticatedFriendsFriendIdRoute,
  AuthenticatedGiftIdRoute: AuthenticatedGiftIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
